# Generated by Django 4.2 on 2023-05-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_category_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='catgory',
            new_name='category',
        ),
    ]
